### ISSUE TITLE
This add-on conflicts with the other add-on

### ISSUE THREAD

**Issue by purequant** [Arthur-Milchior/anki-separate-buttons#1]
When I use this add-on,[Progress Graphs and Stats for Learned and Matured Cards](https://ankiweb.net/shared/info/266436365) it can't work.

When I disable this add-on, Progress Graphs and Stats for Learned and Matured Cards can work so I think this add-on conflict with it

**Comment by Arthur-Milchior** [comment]
Thank you for the information. i'll update the readme page, but currently don't intend to spend the time to look at it. I don't use any of the two add-ons, and mostly works on things I use or which makes some money to me.

**Comment by purequant** [comment]
Thanks, I see. I will try to debug it myself.
